import type { EcommerceSkillDefinition } from "./types";

export const MODEL_INTERACTION_TOP_WEAR: EcommerceSkillDefinition = {
    id: "model-interaction.top-wear",
    version: 1,
    family: "MODEL_INTERACTION",
    mode: "MODEL_INTERACTION",
    name: "Top Wear Model Lifestyle",
    applicability: ["tops, shirts, jackets, sweaters and similar upper-body apparel", "at least one product reference image", "an uploaded or AI-created model brief"],
    executionRules: [
        "preserve the confirmed garment silhouette, neckline, shoulder line, sleeve length, closure and hem",
        "keep one model identity and one wardrobe state across the complete series",
        "change the camera role between slots instead of repeating the same pose and angle",
    ],
    constraints: ["do not invent garment panels, pockets, buttons, logos or prints", "do not distort hands, neck, shoulders, sleeves or garment-to-body contact", "keep the product readable and leave a channel-safe text area"],
    variations: [
        {
            id: "hero-full-body",
            camera: "full-body eye-level three-quarter view",
            lighting: "soft natural key light from camera left",
            composition: "model placed on the right third with a calm leading line",
            productPlacement: "garment fully visible from neckline to hem",
            surface: "realistic lifestyle floor or ground plane",
            props: ["one scene-matched everyday prop"],
            support: "natural standing weight and believable foot contact",
            orientation: "front three-quarter garment view",
            logoVisibility: "visible when present without redraw",
            textSafeZones: ["upper left"],
        },
        {
            id: "environment-wide",
            camera: "wide environmental view from a slightly lower eye line",
            lighting: "soft directional daylight with visible room depth",
            composition: "model integrated into the scene with negative space for copy",
            productPlacement: "garment remains identifiable at environmental scale",
            surface: "scene-specific floor, pavement or interior ground",
            props: ["two restrained lifestyle props"],
            support: "natural walking or paused movement with stable contact",
            orientation: "side-forward garment orientation",
            logoVisibility: "preserve visible branding without exaggeration",
            textSafeZones: ["right half"],
        },
        {
            id: "medium-relation",
            camera: "waist-up medium portrait with a mild three-quarter angle",
            lighting: "soft window light with controlled background separation",
            composition: "garment and model relationship centered with breathing room",
            productPlacement: "neckline, shoulder construction and upper torso readable",
            surface: "quiet scene background with real depth",
            props: ["one held or nearby context prop"],
            support: "relaxed shoulder and arm posture",
            orientation: "front-facing upper garment view",
            logoVisibility: "clear if it is part of the reference",
            textSafeZones: ["lower right"],
        },
        {
            id: "natural-action",
            camera: "dynamic mid-length candid action frame",
            lighting: "consistent daylight with a soft moving shadow",
            composition: "single natural action with the garment as the subject",
            productPlacement: "show how the fabric falls during the action",
            surface: "continuous scene surface matching the hero frame",
            props: ["one prop that explains the action"],
            support: "hands and garment contact follow real force and tension",
            orientation: "action three-quarter garment view",
            logoVisibility: "do not hide or duplicate visible marks",
            textSafeZones: ["upper right"],
        },
        {
            id: "fabric-detail",
            camera: "tight chest-to-hip editorial detail crop",
            lighting: "soft raking light revealing weave and construction",
            composition: "detail crop with a clean edge and no accidental occlusion",
            productPlacement: "fabric texture, seam and closure occupy the frame",
            surface: "same wardrobe and scene continuity as the hero",
            props: [],
            support: "natural garment drape without floating fabric",
            orientation: "detail angle chosen to show the confirmed feature",
            logoVisibility: "preserve real logo shape and placement",
            textSafeZones: ["left edge"],
        },
        {
            id: "back-support",
            camera: "rear or side-back three-quarter view",
            lighting: "same scene light direction with a gentle rim",
            composition: "back construction fills the frame without repeating the hero angle",
            productPlacement: "back, side seam and hem remain visible",
            surface: "continuous environment and matching ground contact",
            props: ["one distant scene prop"],
            support: "natural turn with correct shoulder and sleeve behavior",
            orientation: "back three-quarter garment view",
            logoVisibility: "retain any confirmed back branding",
            textSafeZones: ["lower left"],
        },
    ],
    relationTemplates: [
        { from: "{{model}}", relation: "wears", to: "{{product}}" },
        { from: "{{garment}}", relation: "follows", to: "{{body}}" },
        { from: "{{hands}}", relation: "contacts_naturally", to: "{{garment}}" },
        { from: "{{product}}", relation: "exists_in", to: "{{scene}}" },
        { from: "{{logo}}", relation: "visible_from", to: "{{camera}}" },
    ],
    promptTemplate:
        "Commercial lifestyle apparel photograph. Preserve {{product}} and the same {{model}} identity. {{camera}}; {{lighting}}; {{composition}}; {{productPlacement}}. Keep {{scene}} continuous, keep {{logo}} accurate, and leave {{textSafeZone}} clear.",
};
