import type { EcommerceSkillDefinition } from "./types";

export const STILL_LIFE_LIFESTYLE_TABLETOP: EcommerceSkillDefinition = {
    id: "still-life.lifestyle-tabletop",
    version: 1,
    family: "STILL_LIFE",
    mode: "STILL_LIFE",
    name: "Lifestyle Tabletop",
    applicability: ["physical product with a visible front or hero surface", "product image has at least one usable source asset"],
    executionRules: ["preserve confirmed product facts", "keep the product as the visual hero", "vary one composition axis per variation"],
    constraints: ["do not invent logo text", "do not occlude the product hero surface", "keep a clean text-safe zone"],
    variations: [
        {
            id: "hero-front",
            camera: "front three-quarter product view",
            lighting: "soft window light from camera left",
            composition: "hero product on the visual centerline",
            productPlacement: "centered on the tabletop",
            surface: "warm matte stone tabletop",
            props: ["one restrained botanical accent"],
            support: "stable tabletop contact",
            orientation: "front label toward camera",
            logoVisibility: "clear and unobstructed",
            textSafeZones: ["upper right"],
        },
        {
            id: "side-light",
            camera: "low three-quarter product view",
            lighting: "directional side light with a soft shadow",
            composition: "product offset left with negative space",
            productPlacement: "left third of the tabletop",
            surface: "neutral textured tabletop",
            props: ["one material-matched prop"],
            support: "stable tabletop contact",
            orientation: "front label angled toward camera",
            logoVisibility: "visible from camera",
            textSafeZones: ["right half"],
        },
        {
            id: "overhead-context",
            camera: "controlled overhead tabletop view",
            lighting: "even diffuse studio light",
            composition: "product with a small contextual prop cluster",
            productPlacement: "centered within a designed flat lay",
            surface: "clean warm neutral surface",
            props: ["two restrained contextual props"],
            support: "flat stable surface",
            orientation: "hero surface toward camera",
            logoVisibility: "clear and unobstructed",
            textSafeZones: ["lower third"],
        },
        {
            id: "detail-hero",
            camera: "tight editorial three-quarter crop",
            lighting: "soft specular highlight with controlled falloff",
            composition: "close hero crop with breathing room",
            productPlacement: "slightly right of center",
            surface: "minimal matte surface",
            props: [],
            support: "stable tabletop contact",
            orientation: "key feature toward camera",
            logoVisibility: "visible without distortion",
            textSafeZones: ["left third"],
        },
    ],
    relationTemplates: [
        { from: "{{product}}", relation: "rests_on", to: "{{surface}}" },
        { from: "{{props}}", relation: "does_not_occlude", to: "{{product}}" },
        { from: "{{logo}}", relation: "visible_from", to: "{{camera}}" },
    ],
    promptTemplate: "Commercial tabletop product photograph. Preserve {{product}} identity and {{logo}}. {{camera}}; {{lighting}}; {{composition}}; {{surface}}. Keep {{textSafeZone}} clear.",
};
